name: C/C++ CI

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: gcc lib/static.c -o static && ./static -c
    - name: configure
      run: ./configure > /dev/null
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
